Update adapter to work with EC3 API Update
BHoM/CarbonQueryDatabase_Toolkit pull request #108
Opened 2023-06-08 18:20 UTC by michaelhoehn

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #107 

### Test files

### Changelog

### Additional comments

2023-06-08 18:24 UTC, FraserGreenroyd commented on CarbonQueryDatabase_Engine/Compute/APIToken.cs
> +        [PreviousVersion("6.2", "BH.Engine.Adapters.CarbonQueryDatabase.CQDBearerToken(string username = \"\", string password = \"\")")]
```suggestion
        [PreviousVersion("6.2", "BH.Engine.Adapters.CarbonQueryDatabase.CQDBearerToken(System.String, System.String)")]
```

2023-06-08 18:25 UTC, FraserGreenroyd commented on CarbonQueryDatabase_Engine/Create/GetRequest.cs
> +        [PreviousVersion("6.2", "BH.Engine.Adapters.CarbonQueryDatabase.CarbonQuery(string username = \"\", string password = \"\"), BH.oM.Adapters.CarbonQueryDatabase.CQDConfig parameters = null")]
```suggestion
```

The signature hasn't changed so no previous version attribute needed.

2023-06-08 18:48 UTC, michaelhoehn commented
@BHoMBot check versioning

2023-06-08 19:27 UTC, FraserGreenroyd requested changes

2023-06-08 19:27 UTC, FraserGreenroyd commented on CarbonQueryDatabase_Adapter/CarbonQueryDatabase_Adapter.cs
> +        [PreviousVersion("6.2", "BH.Adapter.CarbonQueryDatabase(System.String, System.String, System.Bool)")]
```suggestion
        [PreviousVersion("6.2", "BH.Adapter.CarbonQueryDatabaseAdapter(System.String, System.String, System.Bool)")]
```

2023-06-08 19:27 UTC, FraserGreenroyd commented on CarbonQueryDatabase_Engine/Compute/APIToken.cs
> +        [PreviousVersion("6.2", "BH.Engine.Adapters.CarbonQueryDatabase.CQDBearerToken(System.String, System.String)")]
```suggestion
        [PreviousVersion("6.2", "BH.Engine.Adapters.CarbonQueryDatabase.Compute.CQDBearerToken(System.String, System.String)")]
```

2023-06-08 19:32 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-06-08 20:05 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-06-08 21:00 UTC, michaelhoehn commented
@BHoMBot check versioning

2023-06-08 22:07 UTC, FraserGreenroyd commented
@BHoMBot check compliance
@BHoMBot check required

2023-06-08 22:37 UTC, FraserGreenroyd approved these changes
File changes make sense, great work @michaelhoehn

2023-06-08 22:38 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-06-09 01:25 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 14120375309

2023-06-09 01:25 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 14120370226

2023-06-09 01:25 UTC, merged